name: pizaa_repoo
description: "repo that handles pizaa"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

path:
dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  equatable:
  firebase_storage:
  rxdart:
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true